//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Y4e6na9Practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Application_Submission = new HashSet<Application_Submission>();
            this.LoggerUser = new HashSet<LoggerUser>();
        }
    
        public int Users_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Roles_ID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Phone { get; set; }
        public string SecondName { get; set; }
        public string Patronymic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Submission> Application_Submission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoggerUser> LoggerUser { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
